source 'https://cdn.cocoapods.org/'

platform :ios, '10.0'

use_frameworks!

target 'DVIA-v2' do
    pod 'Parse', '1.17.3'
    pod 'GoogleAnalytics', '3.17.0'
    pod 'RealmSwift', '4.1.1'
    pod 'couchbase-lite-ios', '1.4.4'
    pod 'Flurry-iOS-SDK/FlurrySDK', '10.0.2'
end

